### PR TITLE
M3 refactoring

### PR DESCRIPTION
**Pull request by hluchas**
https://backlog.acquia.com/browse/MAUT-3157

I've no idea where to get some credentials and test it for now.

### CODE REVIEW

**Review by mtshaw3 — APPROVED** [review]
Code changes look good, config form loads fine. Unable to test further without credentials

**Comment by hluchas** [comment]
> Code changes look good, config form loads fine. Unable to test further without credentials

I asked for credentials here https://acquia.slack.com/archives/GJX018737/p1577444777010400

**Comment by hluchas** [comment]
@alanhartless asked for credentials by mail. https://acquia.slack.com/archives/GJX018737/p1577444777010400

**Comment by hluchas** [comment]
The last mention about future of Slooce plugin is here https://acquia.slack.com/archives/GJX018737/p1577467677015500?thread_ts=1577444777.010400&cid=GJX018737

**Comment by hluchas** [comment]
Closing. Can be found here on github in the future

**Pull request closed without merging**
